# This file was generated by GoReleaser. DO NOT EDIT.
cask "taracode" do
  version "3.1.0"

  on_macos do
    on_arm do
      sha256 "adcceed0f5c680ffbbb01146696c540fe5786da8b668e0c4d2e6bdce8f49093d"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-darwin-arm64"
      binary "taracode-darwin-arm64", target: "taracode"
    end
    on_intel do
      sha256 "9b31e33db1bbb244bb5b1426b77a381144002157e4fc221c57541b0fc08b1cfe"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-darwin-amd64"
      binary "taracode-darwin-amd64", target: "taracode"
    end
  end
  on_linux do
    on_arm do
      sha256 "8bb32181da5c04492945053dc376f2227584e58a1e246158fd5dec139e91eb8e"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-linux-arm64"
      binary "taracode-linux-arm64", target: "taracode"
    end
    on_intel do
      sha256 "2a28b4a60600943e7eea607c6b7b4a711b9e40600669b594334622096e2cbfc1"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-linux-amd64"
      binary "taracode-linux-amd64", target: "taracode"
    end
  end

  name "taracode"
  desc "DevOps and Cloud AI assistant that runs locally with Ollama"
  homepage "https://github.com/tara-vision/taracode"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      Dir["#{staged_path}/taracode-darwin-*"].each do |bin|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", bin]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    taracode needs Ollama and a tool-capable model:

      brew install ollama
      ollama pull gemma4:12b      # 16 GB machines
      ollama pull glm-4.7-flash   # 32 GB machines (Ollama 0.14.3 or newer)

    Then run `taracode` inside a project directory.
  EOS
end
