# This file was generated by GoReleaser. DO NOT EDIT.
cask "taracode" do
  version "3.0.0"

  on_macos do
    on_arm do
      sha256 "f50374eb379b5787c5b0c3fc937f0f19c686c5f1656f40475b522758c980c5f5"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-darwin-arm64"
      binary "taracode-darwin-arm64", target: "taracode"
    end
    on_intel do
      sha256 "157d981de313fccb3c909d7a8a79d02af6c84b846c8c0b47bd102fe04a65cb25"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-darwin-amd64"
      binary "taracode-darwin-amd64", target: "taracode"
    end
  end
  on_linux do
    on_arm do
      sha256 "fdac45ad1ad9f391d92cb7042c9ba6ac1a0612c790c93b6e27a8edc37722c21c"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-linux-arm64"
      binary "taracode-linux-arm64", target: "taracode"
    end
    on_intel do
      sha256 "7b63a49a16b83e2da57cc875aa1572b556f7dc3cd571bc91455b030fc7ecd7b8"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-linux-amd64"
      binary "taracode-linux-amd64", target: "taracode"
    end
  end

  name "taracode"
  desc "DevOps and Cloud AI assistant that runs locally with Ollama"
  homepage "https://github.com/tara-vision/taracode"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      Dir["#{staged_path}/taracode-darwin-*"].each do |bin|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", bin]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    taracode needs Ollama and a tool-capable model:

      brew install ollama
      ollama pull gemma4:12b      # 16 GB machines
      ollama pull glm-4.7-flash   # 32 GB machines (Ollama 0.14.3 or newer)

    Then run `taracode` inside a project directory.
  EOS
end
