# This file was generated by GoReleaser. DO NOT EDIT.
cask "taracode" do
  version "3.2.2"

  on_macos do
    on_arm do
      sha256 "7d6e8f38f5baccb6933dcb34c598d600b66294593804383ed691e2c9922d69aa"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-darwin-arm64"
      binary "taracode-darwin-arm64", target: "taracode"
    end
    on_intel do
      sha256 "b8f1fb77617e4e69a2c804874b5164cf0022d336b5f60604529f35d20b8fa416"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-darwin-amd64"
      binary "taracode-darwin-amd64", target: "taracode"
    end
  end
  on_linux do
    on_arm do
      sha256 "525f1336cf29c030c2dde69f13eaf020f132192c7d565b24ce29d940bf8a7fa7"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-linux-arm64"
      binary "taracode-linux-arm64", target: "taracode"
    end
    on_intel do
      sha256 "8a051591f7e11ca9ee3c6d738501539fc376a377a737bba28fe22269f0ecc577"
      url "https://github.com/tara-vision/taracode/releases/download/v#{version}/taracode-linux-amd64"
      binary "taracode-linux-amd64", target: "taracode"
    end
  end

  name "taracode"
  desc "DevOps and Cloud AI assistant that runs locally with Ollama"
  homepage "https://github.com/tara-vision/taracode"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      Dir["#{staged_path}/taracode-darwin-*"].each do |bin|
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", bin]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    taracode needs Ollama and a tool-capable model:

      brew install ollama
      ollama pull gemma4:12b      # 16 GB machines
      ollama pull glm-4.7-flash   # 32 GB machines (Ollama 0.14.3 or newer)

    Then run `taracode` inside a project directory.
  EOS
end
