name: Formula Issue
description: Report a problem with the Homebrew formula installation
title: "[Formula]: "
labels: ["formula"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue with the Homebrew formula!

        **Note:** For issues with the Tara Code application itself (after installation), please report at [tara-vision/taracode](https://github.com/tara-vision/taracode/issues).

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: A clear and concise description of the problem.
      placeholder: Describe the issue...
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      options:
        - Installation failure
        - Checksum mismatch
        - Build error
        - Formula syntax error
        - Other
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command Run
      description: What command did you run?
      placeholder: "brew install tara-vision/taracode/taracode"
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Output/Error Message
      description: Please copy and paste the full output or error message.
      render: shell
    validations:
      required: true

  - type: input
    id: macos-version
    attributes:
      label: macOS Version
      description: Output of `sw_vers -productVersion`
      placeholder: "14.0"
    validations:
      required: true

  - type: input
    id: brew-version
    attributes:
      label: Homebrew Version
      description: Output of `brew --version`
      placeholder: "Homebrew 4.2.0"
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      options:
        - Apple Silicon (arm64)
        - Intel (x86_64)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
